version: "3.8"

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "./backend:/usr/src/app/backend"
      - "/usr/src/app/backend/node_modules"
    ports:
      - 5001:5001
    environment:
      - NODE_ENV=development
      - PORT_SERVER=5001
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/usr/src/app/frontend"
      - "/usr/src/app/frontend/node_modules"
    ports:
      - 3001:3000
    depends_on:
      - server
    environment:
      - NODE_ENV=development
