version: "3.8"

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - ./backend:/usr/src/app
    ports:
      - 5001:5000
    environment:
      - NODE_ENV=development
      - PORT_SERVER=5000
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - HOST_WS=ws://server:5001
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    ports:
      - 3001:3000
    depends_on:
      - server
    environment:
      - NODE_ENV=development
      - REACT_APP_HOST_WS=ws://server:5001
      - NODE_OPTIONS=--openssl-legacy-provider
    # command: echo HOST_WS=ws://server:5001 >> .env
